name: Galiano Island English Hagwon
favicon: null
layout_spectrum: 0.49398
typography_spectrum: 0.32126
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#175a05'
    - '#b5881c'
    - '#000000'
    - '#071c01'
    - '#7c5d13'
  brandStrength: 0.4879228409845382
  lightness: 0.7533676095772535
  saturation: 0.22728066029958427
  rhythmicContrast: 0.29134283890016377
purpose: []
